# Generated by Django 5.1.2 on 2024-11-02 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sharedfile',
            name='file',
        ),
        migrations.RemoveField(
            model_name='sharedfile',
            name='shared_with',
        ),
        migrations.DeleteModel(
            name='LinkShare',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='SharedFile',
        ),
    ]
